Validating 247192 image pairs...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 247192/247192 [00:07<00:00, 34311.53it/s]
Found 247192 valid pairs
Validating 52872 image pairs...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 52872/52872 [00:01<00:00, 27682.30it/s]
Found 52872 valid pairs
Traceback (most recent call last):
  File "/mimer/NOBACKUP/groups/naiss2023-22-1358/samir_code/kinship_project/src/kinship_deepface.py", line 274, in <module>
    main()
  File "/mimer/NOBACKUP/groups/naiss2023-22-1358/samir_code/kinship_project/src/kinship_deepface.py", line 261, in main
    model, history = train_model(config)
                     ^^^^^^^^^^^^^^^^^^^
  File "/mimer/NOBACKUP/groups/naiss2023-22-1358/samir_code/kinship_project/src/kinship_deepface.py", line 219, in train_model
    tf.keras.callbacks.ModelCheckpoint(
  File "/mimer/NOBACKUP/groups/naiss2023-22-1358/samir_code/kinship_project/kinship_venv_n/lib/python3.12/site-packages/keras/src/callbacks/model_checkpoint.py", line 191, in __init__
    raise ValueError(
ValueError: The filepath provided must end in `.keras` (Keras model format). Received: filepath=/mimer/NOBACKUP/groups/naiss2023-22-1358/samir_kinship_model/kinship_facenet512_pretrained/checkpoints/checkpoint_{epoch:02d}
